default:
  def_chat_color: black
  def_chat_bk_color: gray80
  
  user:
    name: User
    chat_color: black
      
  actor:
    path: ./models/Idefics2-8B-Instruct_Car
    
settings:
  actor_data: actor_data.yaml # モデル設定ファイル名
  actor_auto_load: True # モデル自動読み込み
  thread_model_load: True # モデルロード時にモデルを別スレッドでロード
  random_seed: -1 # ランダムシード値(-1は完全ランダム)
  use_cpu_flg: False # CPU使用
  chat_color_flg: True # フォントの文字色を変更
  master_size: [800, 600] # 初期メイン画面サイズ
  actor_win_size: [220, 220] # キャラウィンドウ画像サイズ
  chat_canv_flg: False # チャットのキャンパスを初期表示(Falseのときは非表示)
  img_redraw_msec: 16 # # メイン画像再描画時間(ミリ秒)
  max_tokens:  256 # 最大トークン数
  chat_hist_flg: True # チャット履歴の有無
  max_sentences: 5 # 最大行数(通常チャット時)
  max_sentences_hist: 5 # 返信の最大行数(履歴チャット時)
  chat_view_sec: 0.02 # 返信メッセージが画面に表示される間隔
  new_line_num: 0 # チャットの会話間隔(空行数)
  def_cuda_num: 0 # デフォルトのメインCuda番号
  def_sub_cuda_num: 1 # デフォルトのサブCuda番号
  status_bar_flg: True # ステータスバーの表示
  status_bar_msg_msec: 10000 # ステータスバーのメッセージ表示時間
  chat_datetime_flg: True # チャット時に日付日時を取得する
  no_chat_key: ※ # 先頭にこの文字が入っていたら応答なしとなる文字
  chat_split_key: --- # チャットを区切る文字列
  name_no_msg_flg: True # 名前をメッセージに含めない
  input_image_max: 1024 # 入力画像の最大サイズ

form:
  font: # フォント
    form: [meiryo, 10] # フォーム
    prof: [meiryo, 9] # プロフィール
  color_txt_chat: "gray97"

log:
  output_flg: False
  path: ./log
